### ISSUE TITLE
[DMCA]

### ISSUE THREAD

**Issue by Patheticlol** [developer-lfierrro743/Project-EaglercraftY-1.9.4-version#50]
Please take this shitty source code down, or I will have to file a DMCA request.

**Comment by pickle69420** [comment]
Why tho? Not like you can do shit either.

**Comment by OtterCodes101** [comment]
that was made when this repo had the 1.9.4 JAR

**Comment by unspeakfan** [comment]
just leave lfierro alone, he is just trying to let us have fun

**Comment by OtterCodes101** [comment]
what do you mean by that?

**Comment by unspeakfan** [comment]
he is being nice by giving us a free version of minecraft. we need to be
thankful instead of criticizing him

**Comment by OtterCodes101** [comment]
no he's not. he hasn't even gotten any code done yet and the "screenshot" is photoshopped.
if you want a REAL eagler project, go [here](https://github.com/EaglerReborn)

**Comment by unspeakfan** [comment]
is there a replit version for it

**Comment by Patheticlol** [comment]
JUST DELETE THE FUCKING REPo
